### ISSUE TITLE
Logitech G935 Wireless Headset

### ISSUE THREAD

**Issue by ashaikh** [mijorus/whisper#10]
Not sure if this is a bug or not but I installed it per your instructions and on a logitech headset none of the devices show in the system settings of your app for microphone or speaker. I am on Ubuntu 22.04 with the latest updates. Pipewire and pulseaudio are installed. I installed via Flatpak.

Thanks

**Comment by mijorus** [comment]
Hi,
Is it Bluetooth?

**Comment by ashaikh** [comment]
It has its own dongle for longer range but it is similar to bluetooth. I also tested by plugging in a normal usb speaker and it also does not show up. I will try a hard wired mic in a few hours and let you know.

**Comment by mijorus** [comment]
sorry for the delay @ashaikh , could you please paste (or send) the "debug log" file? 
You can open it from the hamburger menu.

**Comment by mijorus** [comment]
@ashaikh your device could simply have been blacklisted (by me) for some reason. If you could send  the output of the debug file, I'll look into that.
