### ISSUE TITLE
Is the application name translatable?

### ISSUE THREAD

**Issue by sabriunal** [mijorus/whisper#11]
Hi, I have translated Whisper to Turkish.

I have a question. Is it possible to translate the application name (Whisper)?

It's not necessary to translate the application name but some developers allow it.

**Comment by sabriunal** [comment]
@mijorus I'll be wating your answer before sending Turkish translation.

Thanks.

**Comment by mijorus** [comment]
Hi @sabriunal, no I don't want the app name to be translated, I think it makes the app more recognisable.
