### ISSUE TITLE
Issue with runtime

### ISSUE THREAD

**Issue by charliebarkin2023** [mijorus/whisper#18]
Info: runtime org.gnome.Platform branch 43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   it.mijorus.whisper

Please update your runtime to Gnome 44 and above. Thanks

**Comment by mijorus** [comment]
The latest updates have bumped the required runtime

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
