### ISSUE TITLE
Set output delay

### ISSUE THREAD

**Issue by dusansimic** [mijorus/whisper#3]
First of all, thanks for creating a fantastic GNOME native app for testing the microphone 😁.

I'm interested whether it's possible to set the output delay. If I'm not mistaken, you use `pw-link` to connect microphone directly to the output but I can't find out if it's possible to do that.

**Comment by mijorus** [comment]
It is definitely possible in some way, but I don't see the reason for this kind of application

**Comment by dusansimic** [comment]
Sorry I didn't specify that in the initial submission. I'm personally having trouble listening to what's microphone picking up and speaking at the same time. I feel that some delay could help out with this.

**Comment by pesader** [comment]
Is it possible to add the delay only between the microphone-speaker (or the microphone-headphone) connection, so as to not affect other applications?
