### ISSUE TITLE
Should connections be released when Whisper is closed? 

### ISSUE THREAD

**Issue by mijorus** [mijorus/whisper#4]
Let me know what you think

**Comment by dusansimic** [comment]
I think so 😁. I was surprised that they are not released on app close. If the app is meant for checking whether microphone works and what it's recording by playing the input on a specified output, it would probably be expected that it stops doing that once closed.

**Comment by mijorus** [comment]
I originally designed it as a replacement for Helvum, that's why it does't do that.

**Comment by rene-coty** [comment]
Maybe this should be an option in the preferences window.. I must admit I was also surprised that the app didn't automatically release connections when closed, but if it's intentional, then the possibility should still exist

**Comment by mijorus** [comment]
> Maybe this should be an option in the preferences window.. I must admit I was also surprised that the app didn't automatically release connections when closed, but if it's intentional, then the possibility should still exist

This feature is coming in the next update
